int print_char(char c);
void print_tab(char **split);
void free_tab(char **split);
char *read_line(const int fd);
char **string_split(const char *str, char space);
int shell_execute(char **, char ***, char **, char **, char **);
int shell_fork_and_run(char **, char **);
char *search_dir(char **args, char **envp);
char *get_index(char *source, char character);
char **copy_envp(char *envp[]);
int write_to_str(char *source, char *dest, char term);
int string_length(char *str);
int write_to_index(char *source, char *dest, char term, char index);
void length(const int fb, int count, char **line, char check);
char *length_string_word(char *str, char *dest, char space);
char *string_word_copy(char *src, char *dest, char space);
char *go_through_spaces(char *str, char space);
char **store_number_of_strings(char *str, char space);
void print_line(char *line);
int string_ncompare(const char *s, const char *t, int n);
char *dir_path(char *s1, char *s2);
char *get_env(char *name, char **envp);
int string_length(char *str);
